spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user_service
    username: postgres
    password: 1234

jwt:
  access:
    secret:
      key: dGhpcy1pcy1hLXN1cGVyLXNlY3VyZS1hbmQtbG9uZy10ZXN0LWtleS1mb3Itand0
  refresh:
    secret:
      key: YS1kaWZmZXJlbnQtc3VwZXItc2VjdXJlLWFuZC1sb25nLXRlc3Qta2V5LWZvci1yZWZyZXNo

crypto:
  key: lGCfIAPebEerr2SH6W4Jy/63+K46CvAnWJkvFOPLIbo=

custom:
  global:
    internalBackUrl: http://localhost:${server.port:8080}